export const actionTypes = {
	INITIALIZE_CINEMAGRAPH_CANVAS: 'INITIALIZE_CINEMAGRAPH_CANVAS',
	SELECT_CINEMAGRAPH_VIDEO: 'SELECT_CINEMAGRAPH_VIDEO',
	BRUSH_STROKE_COMPLETE: 'BRUSH_STROKE_COMPLETE',
	UNDO_CINEMAGRAPH: 'UNDO_CINEMAGRAPH',
	REDO_CINEMAGRAPH: 'REDO_CINEMAGRAPH',
	RENDER_CINEMAGRAPH: 'RENDER_CINEMAGRAPH',
};

// ACTIONS
export const initializeCinemagraphCanvas = () => {
	return { type: actionTypes.INITIALIZE_CINEMAGRAPH_CANVAS};
}

export const selectCinemagraphVideo = (files) => {
	return { type: actionTypes.SELECT_CINEMAGRAPH_VIDEO, files: files };
}