export const INITIALIZE_CINEMAGRAPH_CANVAS = 'INITIALIZE_CINEMAGRAPH_CANVAS';
export const SELECT_CINEMAGRAPH_VIDEO = 'SELECT_CINEMAGRAPH_VIDEO';
export const BRUSH_STROKE_COMPLETE = 'BRUSH_STROKE_COMPLETE';
export const UNDO_CINEMAGRAPH = 'UNDO_CINEMAGRAPH';
export const REDO_CINEMAGRAPH = 'REDO_CINEMAGRAPH';
export const RENDER_CINEMAGRAPH = 'RENDER_CINEMAGRAPH';

